# @package _global_
dataset:
  datasets:
  - churchland.*
  - gallego.*
  - dyer_co.*
  - delay.*
  - miller.*
  - flint.*
  - rouse.*
  - chase.*
  - perich.*

  - schwartz.* # about 730h

  # Eval sets
  - flint.*
  # - chase_Rocky.* # Included in Chase above

  # New in V6
  - batista-Earl-Iso.* # Sorted