# @package _global_
dataset:
  datasets:
  # 1kh? TODO vet that time
  - churchland.*
  - gallego.*
  - dyer_co.*
  - delay.*
  - miller.*
  - Rouse_A.*
  - Rouse_B.* # misses P/Q.
  - perich.* # About 170h
  - chase.*

  - limblab.* # about 650h
  - hatsopoulos.* # about 140h
  # ends up about 1100 hours

  # Eval sets
  - flint.*
  # - chase_Rocky.* # Included in Chase above

  # New in V6
  - batista-Earl-Iso.* # Sorted