# @package _global_

defaults:
  - _default
  - _45m
  - _min
train:
  batch_size: 64
  effective_batch_size: 128

model:
  task:
    task_weights: [1.0, 10.0, 0., 0.] # Scale up spike loss to be comparable to neural loss
    block_prefix_loss: True

notes: "Sweep: Mask ratio low end x Prefix Ratio frequency. Mask ratio high end validated as important in early experiments."
sweep_cfg: "masking"