# @package _global_

defaults:
  - _100

# Hm, it seems most "fair" to keep PT settings in tuning, and only show shift at eval.
model:
  kinematic_token_maskout_schedule: "constant"
  kinematic_token_maskout: 0.

inherit_exp: "v5/ablate"