# @package _global_

defaults:
  - ../_default
dataset:
  behavior_dim: 3
  explicit_alias_to_session: true
  rand_augmentations: ['explicit_crop_time']
  # Need rand_augmentations, not augmentations - name change
  augment_crop_length_ms: 1000
  falcon_m2:
    respect_trial_boundaries: False
    chop_size_ms: 2000
  datasets:
  - falcon_FALCONM2.*
