# @package _global_

# POYO attempted reproduction within NDT3 / BCI framing
# Made as POYO codebase has take a while to come online, and isn't available yet.
#

defaults:
  - _100
  - ../../_scratch
  - ../_poyo