# @package _global_
dataset:
  datasets:
  # 200h
  - churchland.*
  - gallego.*
  - dyer_co.*
  - delay.*
  - miller.*
  - flint.*
  - Rouse_A.*
  - Rouse_B.* # misses P/Q.
  - chase.*
  - perich.* # About 170h

  - pitt_broad.*
