# @package _global_
dataset:
  datasets:
  # 200h
  - churchland.*
  - gallego.*
  - dyer_co.*
  - delay.*
  - miller.*
  - flint.*
  - rouse.*
  - chase.*
  - perich.* # About 170h

  # 600h?
  - schwartz.*

  # Human bit, 1kh
  - chicago.*
  - pitt_broad.*

  # About 650h
  - limblab.* # Full miller scrape
  - hatsopoulos.* # Full hatsopoulos scrape