# @package _global_

defaults:
  - _default
  - _200h
  - _45m

dataset:
  datasets:
  - Rouse_A.*
  eval_datasets: []
train:
  batch_size: 32
  effective_batch_size: 1024
notes: "Trying to binary search for dataset that achieves parity on crc and nersc."