# @package _global_

defaults:
  - ../_default
dataset:
  behavior_dim: 4
  explicit_norm: './data/calib_pitt_calib_broad_norm.pt'
  pitt_co:
    respect_trial_boundaries: False
    chop_size_ms: 1000
  eval_datasets:
  # End
  - pitt_intra_session_pitt_co_P4Home_52_9$
  - pitt_intra_session_pitt_co_P4Home_53_10$
  - pitt_intra_session_pitt_co_P4Home_54_9$
  - pitt_intra_session_pitt_co_P4Home_55_10$
  - pitt_intra_session_pitt_co_P4Home_56_10$
  - pitt_intra_session_pitt_co_P4Home_58_12$
  eval_ratio: 0.5
  eval_split_continuous: True

# Total about 346 training trials, batch size 32 is fine.
train:
  batch_size: 32
  effective_batch_size: 32
  max_batch_size: 32